blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('my_blog.urls',namespace='my_blog')),
    url(r'^users/', include('users.urls', namespace='users')), 


]

my_blog/urls.py
"""定义my_blog的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
      # 主页
      url(r'^$',views.index,name='index'),
      
      # 显示所有的主题
      url(r'^topics/$',views.topics,name='topics'),

      # 显示主题对应的详细页面
      url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),

      # 用于添加新主题的网页
      url(r'^new_topic/$', views.new_topic, name='new_topic'),
      
      # 用于添加新条目的页面
      url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

      # 用于编辑条目的页面
      url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,name='edit_entry'),

      url(r'^file_input/',views.file_input,name="file_input"),


]

users/urls.py
"""为应用程序users定义URL模式"""


from django.conf.urls import url

from django.contrib.auth.views import login

from . import views


urlpatterns = [
    # 登录页面
    url(r'^login/$', login, {'template_name': 'users/login.html'},name='login'),

    # 注销页面
    url(r'^logout/$',views.logout_view,name='logout'),

    # 注册页面
    url(r'^register/$',views.register,name='register'),
    
]

my_blog/models.py
from django.db import models

from django.contrib.auth.models import User



class Topic(models.Model):
    """用户学习主题"""
   
    text = models.CharField(max_length=200) 
    """记录文本不超过200"""
    
    date_added = models.DateTimeField(auto_now_add=True) 
    """记录保存的时间"""

    owner = models.ForeignKey(User)

    def __str__(self):
        """返回模型的字符表示"""
        return self.text



class Entry(models.Model):
    """学到打有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + "..."






# Create your models here.

users/models.py
from django.db import models

# Create your models here.

my_blog/forms.py
from django import forms
from .models import Topic,Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

my_blog/views.py
from django.shortcuts import render,get_object_or_404

from django.http import HttpResponseRedirect, Http404

from django.core.urlresolvers import reverse

from .models import Topic,Entry

from .forms import TopicForm,EntryForm

from django.contrib.auth.decorators import login_required


def index(request):
    """学习笔记打主页"""
    return render(request,'my_blog/index.html')



def file_input(request):
    if request.method == 'GET':
        a = {'a':'开始上传'}
        return render(request, "my_blog/file_input.html",a)
    else:
        
        file_name = request.FILES.get('file_inputname')
        with open('my_blog/file/'+str(file_name.name),'wb') as f:
            for line in file_name:
                f.write(line)
            
        if file_name:
            a = {'a': str(file_name)+"上传成功"}
        else:
            file_name = "请上传文件"
            a = {'a':str(file_name)}

        return render(request,"my_blog/file_input.html",a)

# from django.views import View
#
# class file_input(View):
#     def get(self,request):
#         return render(request,"my_blog/file_input.html")
#     def post(self,request):
#         a = {'a':"返回"}
#         return render(request,"my_blog/file_input.html",a)



@login_required
def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'my_blog/topics.html',context)




@login_required
def topic(request,topic_id):
    """显示单个主题及其所有的条目"""
    topic = get_object_or_404(Topic,id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries': entries}
    return render(request, 'my_blog/topic.html',context)





@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据,对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('my_blog:topics'))
    context = {'form': form}
    return render(request, 'my_blog/new_topic.html', context)




@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 未提交数据,创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('my_blog:topic',args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'my_blog/new_entry.html', context)





@login_required
def edit_entry(request,entry_id):
    """编辑条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('my_blog:topic',args=[topic.id]))
    
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'my_blog/edit_entry.html',context)









# Create your views here.

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse

from django.contrib.auth import login,logout,authenticate

from django.contrib.auth.forms import UserCreationForm



def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('my_blog:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1']) 
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('my_blog:index'))

    context = {'form':form}
    return render(request,'users/register.html', context)




# Create your views here.

my_blog/templates/my_blog/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记-收藏夹</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  
  <style>
    body{
        padding-top: 17px;
}

  </style>

  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"data-toggle="collapse" data-target="#navbar"aria-expanded="false" aria-controls="navbar">
          </button>
            <a class="navbar-brand" href="{% url 'my_blog:index' %}">Learning Log/学习笔记</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'my_blog:topics' %}">Topics</a>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'my_blog:file_input' %}">文件上传⏫</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li>
              <a>Hello, {{ user.username }}.</a>
            </li>
            <li>
              <a href="{% url 'users:logout' %}">log out/注销</a>
            </li>
          {% else %}
            <li>
              <a href="{% url 'users:register' %}">register/注册</a>
            </li>
            <li>
              <a href="{% url 'users:login' %}">log in/登录</a>
            </li>
          {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
    </div> <!-- /container -->
  </body>
</html>

my_blog/templates/my_blog/edit_entry.html
{% extends "my_blog/base.html"%}

{% block content %}

<p><a href="{% url 'my_blog:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'my_blog:edit_entry' entry.id %}" method='post'>

{% csrf_token %}
{{ form.as_p }}

<button name="submit">save changes</button>
</form>

{% endblock content%}

my_blog/templates/my_blog/file_input.html
{% extends "my_blog/base.html" %}


{% block content %}
    <div>
      <div><a>{{ a }}</a></div>
      <div>
          <p>上传文件
            <form action="{% url "my_blog:file_input" %}"  method='post' enctype="multipart/form-data">
                {% csrf_token %}
                <p><input type="file" name="file_inputname"></p>
                <p><input type="submit" value="开始上传"></p>
            </form>
          </p>
      </div>

    </div>


{##}
{#    <p>上传文件#}
{#        <form action="{% url "my_blog:file_input" %}"  method='post' >#}
{#             {% csrf_token %}#}
{#            <p><input type="file" name="file_inputname"></p>#}
{#            <p><input type="submit" value="开始上传"></p>#}
{#        </form>#}
{#    </p>#}





{% endblock content %}

my_blog/templates/my_blog/index.html
{% extends "my_blog/base.html" %}


{% block header %}

<style type="text/css">

   .carousel .carousel-inner img {
    width: 100%;
   }
  </style>
  <div class="carousel slide" data-ride="carousel" id="imooc-carousel">
   <!--游标-->
   <ol class="carousel-indicators">
    <li data-target="#imooc-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#imooc-carousel" data-slide-to="1"></li>
    <li data-target="#imooc-carousel" data-slide-to="2"></li>
    <li data-target="#imooc-carousel" data-slide-to="3"></li>
   </ol>
   <!--图片-->
   <div class="carousel-inner">
    <div class="item active">
     <a href="##">
      <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1525784702910&di=ed3d4ee04fc0e4753de061bbda35f2d5&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimage%2Fc0%253Dshijue1%252C0%252C0%252C294%252C40%2Fsign%3D55d42195db58ccbf0fb1bd7971b1d64b%2F6d81800a19d8bc3e573f8eed888ba61ea8d345e6.jpg" />
     </a>
    </div>
    <div class="item">
     <a href="##">
      <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1525784595102&di=805e2accaf5153430c48a47612f109b0&imgtype=jpg&src=http%3A%2F%2Fimg4.imgtn.bdimg.com%2Fit%2Fu%3D1430027424%2C1925376426%26fm%3D214%26gp%3D0.jpg" />
     </a>
    </div>
    <div class="item">
     <a href="##">
      <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1525784766586&di=f1cb5fd2eec8429cad3255240bb875a3&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimage%2Fc0%253Dshijue1%252C0%252C0%252C294%252C40%2Fsign%3D3df24b74fa1f3a294ec5dd8df14cd644%2F2cf5e0fe9925bc31edc6eb3254df8db1ca137085.jpg" />
     </a>
    </div>
    <div class="item">
     <a href="##">
      <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1525784801833&di=aef2720e45322b25413271011ea16f97&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimage%2Fc0%253Dshijue1%252C0%252C0%252C294%252C40%2Fsign%3Ddc9bfb260055b31988f48a362bc0e853%2Feac4b74543a98226bca49c008082b9014a90ebb4.jpg" />
     </a>
    </div>
   </div>
   <!--控件-->
   <a class="carousel-control left" href="#imooc-carousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
   </a>
   <a class="carousel-control right" href="#imooc-carousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
   </a>
  </div>

  <script type="text/javascript">
   $('.carousel').carousel({
    interval: 2000
   })
  </script>





  <div class='jumbotron'>
    <h1>Track your learning.</h1>
    <h2>美好生活，记录你的每一天</h2>
    <h3>嘿嘿嘿，小了白了兔，白了白</h3>
    <h4>门里面有...有个鬼</h4>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to makeyour own Learning Log, and list the topics you're learning about.
  </h2>
  <h2>Whenever you learn something new about a topic, make an entrysummarizing what you've learned.
  </h2>

{% endblock content %}

my_blog/templates/my_blog/new_entry.html
{% extends "my_blog/base.html" %}

{% block content %}

<p>
<a href="{% url 'my_blog:topic' topic.id %}">{{ topic }}</a>
</p>

<p>Add a new entry:</p>

<form action="{% url 'my_blog:new_entry' topic.id %}" method='post'>

{% csrf_token %}
{{ form.as_p }}
<button name='submit'>add entry</button>

</form>

{% endblock content %}

my_blog/templates/my_blog/new_topic.html
{% extends "my_blog/base.html" %}

{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
  <form action="{% url 'my_blog:new_topic' %}" method='post'class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
  </form>
{% endblock content %}

my_blog/templates/my_blog/topic.html
{% extends 'my_blog/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'my_blog:new_entry' topic.id %}">add new entry/添加描述</a>
  </p>

{% for entry in entries %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small>
          <a href="{% url 'my_blog:edit_entry' entry.id %}">edit entry/编辑</a>
        </small>
      </h3>
    </div>
  <div class="panel-body" style='display:block;word-break: break-all;word-wrap: break-word;'>
    {{ entry.text|linebreaks }}
  </div>
  </div> <!-- panel -->

{% empty %}
  There are no entries for this topic yet.
{% endfor %}


{% endblock content %}

my_blog/templates/my_blog/topics.html
{% extends "my_blog/base.html" %}

{% block header %}

  <h1>Topics</h1>

{% endblock header %}

{% block content %}
  <ul>
{% for topic in topics %}
    <li>
      <h3>
        <a href="{% url 'my_blog:topic' topic.id %}">{{ topic }}</a>
      </h3>
    </li>
  {% empty %}
    <li>No topics have been added yet.</li>
  {% endfor %}
  </ul>
    <h3>
      <a href="{% url 'my_blog:new_topic' %}">Add new topic
    </h3>



{% endblock content %}

users/templates/users/login.html
{% extends "my_blog/base.html" %}

{% load bootstrap3 %}

{% block header %}

<h2>Log in to your account.</h2>

{% endblock header %}

{% block content %}
 
  <form method="post" action="{% url 'users:login' %}" class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary btn-blue">log in</button>
    {% endbuttons %}

      <input type="hidden" name="next" value="{% url 'my_blog:index' %}" />

  </form>


{% endblock content %}

users/templates/users/register.html
{% extends "my_blog/base.html" %}

{% load bootstrap3 %}

{% block content %}

<form method="post" action="{% url 'users:register' %}">

  {% csrf_token %}
  {{ form.as_p }}

  <button name="submit" style="background-color: dodgerblue">register</button>


  <input type="hidden" name="next" value="{% url 'my_blog:index' %}" />
</form>

<h>增加页面渲染</h>

{% endblock content %}